### ISSUE TITLE
polylith-kaocha tests too much

### ISSUE THREAD

**Issue by SavageMessiah** [imrekoszo/polylith-kaocha#1]
At my company we just switched our clojure codebase over to polylith, using polylith-kaocha as test runner. However, it runs more tests than the default runner.

For example, suppose we have two components A and B, a brick C, and a project P with a dependency relationship like P->C->B->A. What I'm seeing is that if you modify component B only, the tests for A are still run in project P with polylith-kaocha. With the default test runner it only runs the tests for B, C, and P.

I think the issue is that the paths from polylith (the ones printed when passing `:verbose`) contain the test dirs for all components in the dependency tree, regardless of whether that component should be tested or not. In the default runner it then invokes only the needed tests, whereas in polylith-kaocha it looks like you're relying on kaocha to pick up the tests so it's picking up everything regardless of whether it should be tested or not. This rather defeats the purpose of the `poly test` command.

I suspect this can be fixed by making `runner-opts->kaocha-poly-opts` more discriminatory when building `test-paths` but I haven't dug too deeply into how all this works.

**Comment by imrekoszo** [comment]
Thanks for reporting! This is something I haven't thought of so far and will have to double-check how the default test runner does it.

https://github.com/imrekoszo/polylith-kaocha/blob/182e88dfb3aebcc4be321130fd7d0e6e77beafc6/components/kaocha-test-runner/src/polylith_kaocha/kaocha_test_runner/core.clj#L17-L22 is where this is calculated in polylith-kaocha, I suppose paths could further be filtered by cross-checking them with the entities in `changes`, so A in your case would be left out.

You could work around this by supplying your own `runner-opts->kaocha-poly-opts` as described in https://github.com/imrekoszo/polylith-kaocha#hooking-into-parts-of-the-process

Alternatively, you could fork the project and fix it there, in which case I'd be interested in a PR.

**Comment by imrekoszo** [comment]
@SavageMessiah I coded up a change to do this hopefully, in case you want to give it a go, use sha `2dc904b6e3e898bc0d74a78a141fb4179dd5ab43`

**Comment by SavageMessiah** [comment]
@imrekoszo Gave that a try but I get this error
```clojure
#error {
 :cause "Don't know how to create ISeq from: clojure.lang.Symbol"
 :via
 [{:type java.lang.IllegalArgumentException
   :message "Don't know how to create ISeq from: clojure.lang.Symbol"
   :at [clojure.lang.RT seqFrom "RT.java" 557]}]
 :trace
 [[clojure.lang.RT seqFrom "RT.java" 557]
  [clojure.lang.RT seq "RT.java" 537]
  [clojure.core$seq__5467 invokeStatic "core.clj" 139]
  [clojure.core$some invokeStatic "core.clj" 2709]
  [clojure.core$some invoke "core.clj" 2709]
  [clojure.core$comp$fn__5876 invoke "core.clj" 2587]
  [polylith_kaocha.kaocha_wrapper.runner$with_debug_reporter invokeStatic "runner.clj" 14]
  [polylith_kaocha.kaocha_wrapper.runner$with_debug_reporter invoke "runner.clj" 12]
  [clojure.core$update invokeStatic "core.clj" 6231]
  [clojure.core$update invoke "core.clj" 6223]
  [polylith_kaocha.kaocha_wrapper.runner$with_verbosity invokeStatic "runner.clj" 20]
  [polylith_kaocha.kaocha_wrapper.runner$with_verbosity invoke "runner.clj" 17]
  [polylith_kaocha.kaocha_wrapper.runner$in_context_runner$run___142111 invoke "runner.clj" 44]
  [polylith_kaocha.kaocha_wrapper.config$execute_in_config_context$fn__4003 invoke "config.clj" 82]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1990]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1990]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [polylith_kaocha.kaocha_wrapper.config$execute_in_config_context invokeStatic "config.clj" 81]
  [polylith_kaocha.kaocha_wrapper.config$execute_in_config_context invoke "config.clj" 76]
  [polylith_kaocha.kaocha_wrapper.runner$run_tests_with_kaocha invokeStatic "runner.clj" 50]
  [polylith_kaocha.kaocha_wrapper.runner$run_tests_with_kaocha invoke "runner.clj" 48]
  [polylith_kaocha.kaocha_wrapper.runner$run_tests invokeStatic "runner.clj" 56]
  [polylith_kaocha.kaocha_wrapper.runner$run_tests invoke "runner.clj" 54]
  [polylith_kaocha.kaocha_wrapper.interface.runner$run_tests invokeStatic "runner.clj" 6]
  [polylith_kaocha.kaocha_wrapper.interface.runner$run_tests invoke "runner.clj" 5]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.core$apply invoke "core.clj" 662]
  [clojure.core$eval142076$rrapply__142077 invoke "NO_SOURCE_FILE" 0]
  [clojure.core$eval142076 invokeStatic "NO_SOURCE_FILE" 0]
  [clojure.core$eval142076 invoke "NO_SOURCE_FILE" -1]
  [clojure.lang.Compiler eval "Compiler.java" 7194]
  [clojure.lang.Compiler eval "Compiler.java" 7149]
  [clojure.core$eval invokeStatic "core.clj" 3215]
  [clojure.core$eval invoke "core.clj" 3211]
  [clojure.core$eval142074 invokeStatic "NO_SOURCE_FILE" 0]
  [clojure.core$eval142074 invoke "NO_SOURCE_FILE" -1]
  [clojure.lang.Compiler eval "Compiler.java" 7194]
  [clojure.lang.Compiler eval "Compiler.java" 7149]
  [jdk.internal.reflect.NativeMethodAccessorImpl invoke0 "NativeMethodAccessorImpl.java" -2]
  [jdk.internal.reflect.NativeMethodAccessorImpl invoke "NativeMethodAccessorImpl.java" 77]
  [jdk.internal.reflect.DelegatingMethodAccessorImpl invoke "DelegatingMethodAccessorImpl.java" 43]
  [java.lang.reflect.Method invoke "Method.java" 568]
  [polylith.clj.core.common.class_loader$invoke_in_STAR_ invokeStatic "class_loader.clj" 31]
  [polylith.clj.core.common.class_loader$invoke_in_STAR_ doInvoke "class_loader.clj" 27]
  [clojure.lang.RestFn invoke "RestFn.java" 494]
  [polylith.clj.core.common.class_loader$eval_in_STAR_$print_read_eval__287 invoke "class_loader.clj" 49]
  [polylith.clj.core.common.class_loader$eval_in_STAR_ invokeStatic "class_loader.clj" 51]
  [polylith.clj.core.common.class_loader$eval_in_STAR_ invoke "class_loader.clj" 45]
  [polylith.clj.core.common.class_loader$eval_in invokeStatic "class_loader.clj" 61]
  [polylith.clj.core.common.class_loader$eval_in invoke "class_loader.clj" 60]
  [polylith.clj.core.common.interface$eval_in invokeStatic "interface.clj" 22]
  [polylith.clj.core.common.interface$eval_in invoke "interface.clj" 21]
  [polylith.clj.core.test_runner_orchestrator.core$__GT_eval_in_project$fn__9041 invoke "core.clj" 78]
  [polylith_kaocha.kaocha_test_runner.core$apply_in_project invokeStatic "core.clj" 73]
  [polylith_kaocha.kaocha_test_runner.core$apply_in_project invoke "core.clj" 69]
  [polylith_kaocha.kaocha_test_runner.core$create$reify__32197 run_tests "core.clj" 113]
  [polylith.clj.core.test_runner_orchestrator.core$run_tests_for_project_with_test_runner invokeStatic "core.clj" 70]
  [polylith.clj.core.test_runner_orchestrator.core$run_tests_for_project_with_test_runner invoke "core.clj" 59]
  [polylith.clj.core.test_runner_orchestrator.core$run_tests_for_project invokeStatic "core.clj" 114]
  [polylith.clj.core.test_runner_orchestrator.core$run_tests_for_project invoke "core.clj" 86]
  [polylith.clj.core.test_runner_orchestrator.core$run invokeStatic "core.clj" 176]
  [polylith.clj.core.test_runner_orchestrator.core$run invoke "core.clj" 154]
  [polylith.clj.core.test_runner_orchestrator.interface$run invokeStatic "interface.clj" 5]
  [polylith.clj.core.test_runner_orchestrator.interface$run invoke "interface.clj" 4]
  [polylith.clj.core.command.test$run invokeStatic "test.clj" 11]
  [polylith.clj.core.command.test$run invoke "test.clj" 5]
  [polylith.clj.core.command.core$execute invokeStatic "core.clj" 87]
  [polylith.clj.core.command.core$execute invoke "core.clj" 62]
  [polylith.clj.core.command.interface$execute_command invokeStatic "interface.clj" 5]
  [polylith.clj.core.command.interface$execute_command invoke "interface.clj" 4]
  [polylith.clj.core.poly_cli.core$_main invokeStatic "core.clj" 33]
  [polylith.clj.core.poly_cli.core$_main doInvoke "core.clj" 7]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.core$apply invokeStatic "core.clj" 667]
  [clojure.main$main_opt invokeStatic "main.clj" 514]
  [clojure.main$main_opt invoke "main.clj" 510]
  [clojure.main$main invokeStatic "main.clj" 664]
  [clojure.main$main doInvoke "main.clj" 616]
  [clojure.lang.RestFn applyTo "RestFn.java" 137]
  [clojure.lang.Var applyTo "Var.java" 705]
  [clojure.main main "main.java" 40]]}
```

I'll see if I can take a stab at getting this working today as well.

**Comment by SavageMessiah** [comment]
Weirdly, when I switched my deps.edn to point at a local checkout of this repo, rather than setting it to use your branch, I didn't get that error. It's still running all the tests though, so no improvement.

**Comment by imrekoszo** [comment]
@SavageMessiah ah, looks like that's a different error, I managed to repro it just now. Hold on while I fix that :)

**Comment by imrekoszo** [comment]
@SavageMessiah would you mind trying `e1f2f6644cde0ec73fa975174ed41875e3f8ce7d`? That should have this reporter thing fixed. Unfortunately I don't have a workspace at hand that would replicate the problem you described in the OP so I'd appreciate if you could let me know whether this fixes that problem.

**Comment by SavageMessiah** [comment]
@imrekoszo Ok, I figured it would probably be more productive if I made a repro case for you rather than flailing around and trying to fix this myself. Here you go https://github.com/SavageMessiah/polylith-kaocha-issue-repro

Looking at the change you've made so far: IMO you should just trust `projects-to-bricks-to-test` 99% of people are going to be putting their tests in the place polytlith expects them. If not that then I would say the "correct" thing to do would be to make it so that the kaocha test locator is used to determine wether bricks or projects have tests. Not sure if that's feasible though.

**Comment by imrekoszo** [comment]
@SavageMessiah is there a possibility you forgot to push the stable tag there? Should it be on this commit? https://github.com/SavageMessiah/polylith-kaocha-issue-repro/commit/972263932496d85fa49052885a62e5f0a3ed66c2

**Comment by SavageMessiah** [comment]
Oh and to actually answer your question: Your latest change does fix the reporter error, but still doesn't fix the original problem.

@imrekoszo Yup, I forgot to push it. I just did so.

**Comment by imrekoszo** [comment]
> trust `projects-to-bricks-to-test` 99% of people are going to be putting their tests in the place polytlith expects them

Unfortunately I'm in that 1% - I use the `:kaocha.plugin.alpha/spec-test-check` plugin which discovers fn specs in src paths and auto-creates tests from them so I might end up with some bricks that only have those type of tests. Unfortunately, https://github.com/polyfy/polylith/blob/f0d38cb71e9d3f7a620a4baecb491da4aab91edd/components/change/src/polylith/clj/core/change/bricks_to_test.clj#L20 will filter those bricks out.

> If not that then I would say the "correct" thing to do would be to make it so that the kaocha test locator is used to determine wether bricks or projects have tests. Not sure if that's feasible though.

polylith-kaocha uses that exact locator, but that locator needs to be given hints about src and test paths.

I have made some progress, thank you for the repro case. It still isn't done, I will have to rely `project-to-bricks-to-test` to some extent as I realized it does much more in terms of filtering than simply looking at changed bricks.

**Comment by SavageMessiah** [comment]
> Unfortunately I'm in that 1%

Haha well so much for taking the easy road then. I didn't think about the spec-test-check plugin. I'd actually like to start using that myself so I'm glad you're tackling that.

Thanks for all of this by the way. In the end cloverage hated our code and didn't work but switching to kaocha has been a great improvement regardless.

**Comment by imrekoszo** [comment]
Bingo, I think. Check my fork of your repro at https://github.com/imrekoszo/polylith-kaocha-issue-repro

Also, check out in your work project `e408aacd69d7bfe288a349cdd795a286b5e51b59`, which should be the head of my pr.

```
polylith-kaocha-issue-repro$ info
  stable since: 64e0885 | stable-2

  projects: 2   interfaces: 4
  bases:    1   components: 4

  project        alias  status   dev
  ----------------------------   ---
  p +            p       -t-     -t-
  development +  dev     s--     s--

  interface  brick    p    dev
  ----------------   ---   ---
  a          a *     stx   st-
  b          b       st-   st-
  c          c       st-   st-
  s          s *     s--   s--
  -          d       stx   st-
polylith-kaocha-issue-repro$ ws get:changes
{:changed-bases [],
 :changed-components ["a" "s"],
 :changed-files ["components/a/src/fun/a/interface.clj"
                 "components/s/src/fun/s/interface.clj"],
 :changed-or-affected-projects ["development" "p"],
 :changed-projects [],
 :git-diff-command "git diff 64e08856038ff679726e6a37d9b1f65b37b42044 --name-only",
 :project-to-bricks-to-test {"development" [], "p" ["a" "d"]},
 :project-to-indirect-changes {"development" {:src ["d"], :test ["d"]},
                               "p" {:src ["d"], :test ["d"]}},
 :project-to-projects-to-test {"development" [], "p" []},
 :since "stable",
 :since-sha "64e08856038ff679726e6a37d9b1f65b37b42044",
 :since-tag "stable-2"}
polylith-kaocha-issue-repro$ test :project
Projects to run tests from: p

Checking out: https://github.com/imrekoszo/polylith-kaocha at e408aacd69d7bfe288a349cdd795a286b5e51b59
Running tests for the p project using test runner: Polylith built-in clojure.test runner...
Running tests from the p project, including 2 bricks and 1 project: a, d, p

Testing fun.a.interface-test
Important change

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.

Testing fun.d.core-test
Important change

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.

Testing fun.p.core-test
Important change

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.
Running tests for the p project using test runner: Polylith-Kaocha test runner...
--- unit (clojure.test) ---------------------------
fun.d.core-test
  dummy-test
    test SHOULD run

fun.a.interface-test
  dummy-test
    test SHOULD run

fun.p.core-test
  dummy-test
    test SHOULD run
--- generative-fdef-checks (clojure.spec.test.check) ---------------------------
fun.s.interface
  fun.s.interface/s FAIL

Randomized with --seed 2012988914

FAIL in fun.s.interface/s (fun/s/interface.clj:4)
== Checked fun.s.interface/s ================

-- Function spec failed -----------

  (fun.s.interface/s 8)

failed spec. Function arguments and return value

  {:args {:n 8}, :ret 24}

should satisfy

  (fn
   [%]
   (=
    (:ret %)
    (-> % :args :n (* 2))))

-------------------------
Detected 1 error

expected: pos-int?
  actual: {:args {:n 8}, :ret 24}
4 tests, 4 assertions, 1 failures.

Execution time: 5 seconds
polylith-kaocha-issue-repro$
```

**Comment by imrekoszo** [comment]
> cloverage hated our code

polylith-kaocha should support kaocha-cloverage, see how this very project uses it: https://github.com/imrekoszo/polylith-kaocha/blob/master/projects/example/test-resources/polylith-kaocha/example/tests.edn

and https://github.com/imrekoszo/polylith-kaocha/blob/master/projects/example/deps.edn#L15

**Comment by SavageMessiah** [comment]
> Bingo, I think.

Awesome, I'll give it a try tomorrow.

> polylith-kaocha should support kaocha-cloverage

Yeah that's what I tried, based on your examples. The problem wasn't with running cloverage, it was the fact that cloverage's instrumentation broke our code in a ton of baffling ways. It's probably fixable, I just haven't had the time.

**Comment by imrekoszo** [comment]
> ton of baffling ways

yeah, I know what you're talking about

**Comment by SavageMessiah** [comment]
@imrekoszo Strange, I'm still getting the same behavior on my original fork, after updating to that sha above. I don't see any essential difference between mine and yours. Is there something I'm missing?

At first I thought it was still doing it on your fork too but after I fetched the stable-2 tag as well it started working.

**Comment by imrekoszo** [comment]
> updating to that sha

Could you share how your repo looks like once you updated? (tags and everything)

Edit: oh, I see you pushed that to your repo. Let me have a look

**Comment by imrekoszo** [comment]
It appears even poly info considers all bricks should be tested on your repo:

```
9d26a07 update polylith-kaocha 2022-05-19 11:24:47 -0400 (HEAD -> main, upstream/main, upstream/HEAD)
#$ ~/tmp/polylith-kaocha-issue-repro ‹main›
; clojure -M:poly info
  stable since: 9722639 | stable-1

  projects: 2   interfaces: 3
  bases:    1   components: 3

  project        alias  status   dev
  ----------------------------   ---
  p *            p       -t-     ---
  development +  dev     s--     s--

  interface  brick    p    dev
  ----------------   ---   ---
  a          a *     stx   st-
  b          b       stx   st-
  c          c       stx   st-
  -          d       stx   st-
```

**Comment by SavageMessiah** [comment]
Yeah, I just noticed that. I don't understand why, it's the same changes since the stable point.

**Comment by imrekoszo** [comment]
And after reverting to the default test runner, all of those are tested:

```
; gd
workspace.edn --- Clojure
 6        :auto-add false}                                                                                                      6        :auto-add false}
 7  :tag-patterns {:stable "stable-*"                                                                                           7  :tag-patterns {:stable "stable-*"
 8                 :release "v[0-9]*"}                                                                                          8                 :release "v[0-9]*"}
 9  :test {:create-test-runner polylith-kaocha.test-runner/create                                                               9 ; :test {:create-test-runner polylith-kaocha.test-runner/create
10         :polylith-kaocha/config-resource "tests.edn"}                                                                       10 ;        :polylith-kaocha/config-resource "tests.edn"}
11  :projects {"development" {:alias "dev"}                                                                                    11  :projects {"development" {:alias "dev"}
12             "p" {:alias "p"}}}                                                                                              12             "p" {:alias "p"}}}

#$ ~/tmp/polylith-kaocha-issue-repro ‹main*›
; clojure -M:poly test :project
Projects to run tests from: p

Running tests for the p project using test runner: Polylith built-in clojure.test runner...
Running tests from the p project, including 4 bricks and 1 project: a, b, c, d, p

Testing fun.a.interface-test
Important change

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.

Testing fun.b.interface-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.

Testing fun.c.interface-test

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.

Testing fun.d.core-test
Important change

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.

Testing fun.p.core-test
Important change

Ran 1 tests containing 1 assertions.
0 failures, 0 errors.

Test results: 1 passes, 0 failures, 0 errors.

Execution time: 2 seconds
```

**Comment by SavageMessiah** [comment]
I tested with the default runner previously and it did what I expected so the fact that poly thinks that all bricks need to be tested is new.

**Comment by imrekoszo** [comment]
@SavageMessiah I think that's because some of the commits after the stable tag are considered "global" changes, like those to the root deps.edn and poly might want to ensure everything is still in order.

That's why I reordered some of the commits on my fork.

**Comment by imrekoszo** [comment]
Try marking head stable now and add another change to a on top and see how it works.

**Comment by SavageMessiah** [comment]
@imrekoszo Ok, I tagged a new stable point and made a new change and it works as expected. Let me give this a try on the real thing.

**Comment by SavageMessiah** [comment]
Awesome, looks good! :)

**Comment by imrekoszo** [comment]
@SavageMessiah thanks for the help in tracking this down, this in now released in:

```clojure
:git/tag "v0.8.0"
:git/sha "e1b0861"
```

**Comment by tengstrand** [comment]
If the project itself has changed, e.g. its `deps.edn` file, then we run the tests for all its bricks from that project. The reson is that some configuration may affect how the tests are executed.

https://github.com/polyfy/polylith/blob/f0d38cb71e9d3f7a620a4baecb491da4aab91edd/components/change/src/polylith/clj/core/change/bricks_to_test.clj#L31-L32
