### ISSUE TITLE
poly test does not return non-zero on error/failure with polylith-kaocha

### ISSUE THREAD

**Issue by SavageMessiah** [imrekoszo/polylith-kaocha#4]
I'm not sure how I didn't notice this before but `clojure -M:poly test` does not return non-zero on error/failure.
If I run `poly test` (thus bypassing polylith-kaocha) it does what I expect.

**Comment by imrekoszo** [comment]
What if you run `clojure -M:poly test` but configure to use the default test runner in workspace.edn?

**Comment by SavageMessiah** [comment]
Just checked that now. I commented out the `create-test-runner` config and it returned non-zero on failure.

**Comment by imrekoszo** [comment]
Thanks, I'll check that out.

**Comment by imrekoszo** [comment]
Managed to repro it, I'll fix this as soon as possible

**Comment by SavageMessiah** [comment]
Thanks, we've got a workaround in place for our CI so it's not super critical.

**Comment by imrekoszo** [comment]
I hopefully fixed this, see https://github.com/imrekoszo/polylith-kaocha/commit/80a76185a6d3a58ec8553c56b47d349aaad3dc02

Feedback is appreciated

**Comment by SavageMessiah** [comment]
Confirmed fixed, thanks again.
