### ISSUE TITLE
Running from cli tool does not work - class not found

### ISSUE THREAD

**Issue by ieugen** [imrekoszo/polylith-kaocha#5]
Hello,

I want to use this and I've hit an issue. 
I don't know if it's by design but polylith-kaocha does not work if you run it from the cli tool.

I have poly 0.2.15-alpha locally. 
I ran `poly test` and I got an exception.

Initially I thought this was my fault.
But it seems that I have to run `clojure -Srepro -M:poly test <poly test args>` in order for polylith-kaocha to be added to the classpath.

This kind of breaks the promise in polylith that all calls will run the same.

Is this limitation something that can be fixed ? 

```
workspace$ poly test
  Error 109: Invalid test runner configuration for project annotator. Unable to load test runner constructor polylith-kaocha.test-runner/create. Exception: java.io.FileNotFoundException: Could not locate polylith_kaocha/test_runner__init.class, polylith_kaocha/test_runner.clj or polylith_kaocha/test_runner.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
```

**Comment by imrekoszo** [comment]
Hey there. This is actually a limitation. The reason is that one of the extra dependencies needs to be added to the [classpath of the poly tool](https://github.com/imrekoszo/polylith-kaocha#1-add-dep-to-poly-alias).

I am not aware of a way to do that when using a local install of the tool. If you manage to figure it out though, feel free to submit a PR to the readme.

**Comment by imrekoszo** [comment]
Hmm maybe this is possible using JVM_OPTS: https://polylith.gitbook.io/poly/install/install/jvm-options

**Comment by imrekoszo** [comment]
Yeah, doesn't look like it. According to poly's [brew script](https://github.com/polyfy/polylith/blob/master/build/resources/brew/exec#L22) and the rest of the [install docs](https://polylith.gitbook.io/poly/install/install/install-on-linux) `java -jar` is used, which will read the classpath from the jar manifest and ignore any other classpath args passed to java.

This is a limitation of the poly tool itself, not this plugin actually, so in case you really need to be able to invoke it using the installed tool, I recommend you raise an issue with the polylith project.

My personal preference in polylith workspaces is to have the poly tool as an alias so I have in-repo control over its version, hopefully resulting in better reproducibility across environments.

**Comment by ieugen** [comment]
So I asked on clojurians https://clojurians.slack.com/archives/C013B7MQHJQ/p1661273391719899 . 

It seems that the solution is to use clojure -M:poly . 
I think this could be added to the docs since it's not always obvious.

**Comment by ieugen** [comment]
I don't think there is a way to avoid this situation.
This is documented and 
Running with `clojure -M:poly ` is just fine.

**Comment by marksto** [comment]
> My personal preference in polylith workspaces is to have the poly tool as an alias so I have in-repo control over its version, hopefully resulting in better reproducibility across environments.

Well, there are different ways people and projects approach this — from `.tool-versions` (mise-en-place, asdf) to Nix. I'm personally inclined towards these. And, yet again, a Clojure CLI dep is slower-starting comparing to a pre-compiled standalone tool version.

**Comment by imrekoszo** [comment]
@marksto not sure if I understood what you're suggesting?
